doctrine:
    dbal:
        driver: pdo_pgsql
        dbname: '%env(DB_NAME)%'
        host: '%env(DB_HOST)%'
        port: '%env(DB_PORT)%'
        user: '%env(DB_USER)%'
        password: '%env(DB_PASSWORD)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        types:
            question_type: 'App\Testing\Domain\Converter\QuestionTypeEnumConverter'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        default_entity_manager: default
        mappings:
            Users:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Users/Infrastructure/Database/ORM'
                prefix: 'App\Users\Domain\Entity'
                alias: Users
            Testing:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Testing/Infrastructure/Database/ORM'
                prefix: 'App\Testing\Domain\Entity'
                alias: Testing
        controller_resolver:
            auto_mapping: false

